name: Push code to Azure Repos

on:
  push:
    branches:
      - main  # Trigger this workflow when pushing to the main branch (you can change this if needed)

jobs:
  push_to_azure:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Git
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "Booravenu"

      # Add Azure Repos remote
      - name: Add Azure Repos remote
        run: |
          git remote add azure https://$(AZURE_USERNAME):${{ secrets.AZURE_REPOS_PAT }}@dev.azure.com/venubura123/project1/_git/DEMOREPO1

      # Push to Azure Repos
      - name: Push to Azure Repos
        run: |
          git push azure main  # Push to the main branch in Azure Repos

